packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/fixtures/**'
catalog:
  '@ark-ui/react': ^4.2.0
  '@ark-ui/vue': ^4.2.0
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  ai: ^3.4.31
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  vite: ^5.4.10
  vue: ^3.5.12
  zod: ^3.23.8
catalogs:
  vite6:
    vite: ^6.0.0-beta.8
