packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/fixtures/**'
catalog:
  '@ark-ui/react': ^4.5.0
  '@ark-ui/vue': ^4.5.0
  ai: ^4.0.22
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  vite: ^6.0.6
  vue: ^3.5.13
  zod: ^3.24.1
catalogs:
  vite6:
    vite: ^6.0.6
  react18:
    '@types/react': ^18.3.18
    '@types/react-dom': ^18.3.5
    react: ^19.0.0
    react-dom: ^19.0.0
  react19:
    '@types/react': ^19.0.2
    '@types/react-dom': ^19.0.2
    react: ^19.0.0
    react-dom: ^19.0.0
