packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/fixtures/**'
catalog:
  '@ark-ui/react': ^4.4.4
  '@ark-ui/vue': ^4.4.2
  ai: ^4.0.14
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  tailwindcss-animate: ^1.0.7
  vite: ^6.0.3
  vue: ^3.5.13
  zod: ^3.24.1
catalogs:
  vite6:
    vite: ^6.0.3
  react18:
    react: ^18.0.0
    react-dom: ^18.0.0
    '@types/react': ^18.3.15
    '@types/react-dom': ^18.3.4
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
