packages:
  - "apps/*"
  - "packages/*"
  - "!**/test/fixtures/**"
catalog:
  '@ark-ui/react': ^4.1.0
  '@ark-ui/vue': ^4.1.0
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.0
  ai: ^3.4.9
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwind-merge: ^2.5.3
  tailwindcss: ^3.4.13
  tailwindcss-animate: ^1.0.7
  vite: ^5.4.8
  vue: ^3.5.11
  zod: ^3.23.8
