packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/fixtures/**'
catalog:
  '@ai-sdk/anthropic': ^1.2.12
  '@ai-sdk/openai': ^1.3.22
  '@ark-ui/react': ^5.9.2
  '@ark-ui/vue': ^5.9.2
  '@astrojs/check': ^0.9.4
  '@astrojs/markdown-remark': 6.3.2
  '@astrojs/mdx': 4.3.0
  '@astrojs/react': ^4.3.0
  '@astrojs/tailwind': ^6.0.2
  '@astrojs/vue': 5.1.0
  '@biomejs/biome': 1.9.4
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.4
  '@chromatic-com/storybook': ^3.2.6
  '@fontsource-variable/inter': ^5.2.5
  '@nanostores/persistent': ^1.0.0
  '@nanostores/react': ^1.0.0
  '@nanostores/vue': ^1.0.0
  '@shikijs/transformers': ^3.4.2
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.14
  '@storybook/addon-links': ^8.6.14
  '@storybook/addon-onboarding': ^8.6.14
  '@storybook/addon-themes': ^8.6.14
  '@storybook/blocks': ^8.6.14
  '@storybook/react': ^8.6.14
  '@storybook/react-vite': ^8.6.14
  '@storybook/test': ^8.6.14
  '@storybook/vue3': ^8.6.14
  '@storybook/vue3-vite': ^8.6.14
  '@turbo/gen': ^2.5.3
  '@types/hast': ^3.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^20.17.50
  '@types/prompts': ^2.4.9
  '@vitejs/plugin-react': ^4.5.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vue/tsconfig': ^0.7.0
  ai: ^4.3.16
  astro: 5.8.0
  autoprefixer: ^10.4.21
  cac: ^6.7.14
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.5.0
  globby: ^14.1.0
  kleur: ^4.1.5
  lint-staged: ^16.0.0
  lodash-es: ^4.17.21
  lucide-react: ^0.511.0
  lucide-vue-next: ^0.511.0
  mdast-util-mdx: ^3.0.0
  mdast-util-mdx-jsx: ^3.2.0
  mlly: ^1.7.4
  nanostores: ^1.0.1
  nypm: ^0.6.0
  ora: ^8.2.0
  postcss: ^8.5.3
  prompts: ^2.4.2
  prop-types: ^15.8.1
  react-scan: ^0.3.4
  recharts: ^2.15.3
  rimraf: ^6.0.1
  scule: ^1.3.0
  sharp: ^0.34.2
  shiki: ^3.4.2
  simple-git-hooks: ^2.13.0
  storybook: ^8.6.14
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  taze: ^19.1.0
  ts-morph: ^26.0.0
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.3
  typescript: ^5.8.3
  ufo: ^1.6.1
  unist-util-visit: ^5.0.0
  vite: ^6.3.5
  vite-plugin-inspect: 11.1.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.4
  vue: ^3.5.14
  vue-tsc: ^2.2.10
  zod: ^3.25.28
  sherif: latest
  '@typescript/native-preview': latest
catalogs:
  react18:
    '@types/react': ^18.3.22
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1
  react19:
    '@types/react': ^19.1.5
    '@types/react-dom': ^19.1.5
    react: ^19.1.0
    react-dom: ^19.1.0
onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js-pure
  - esbuild
  - sharp
  - simple-git-hooks
