packages:
  - apps/*
  - packages/*
  - tooling/*
  - '!**/test/fixtures/**'
catalog:
  '@ark-ui/react': ^4.9.2
  '@ark-ui/vue': ^4.9.2
  ai: ^4.3.16
  autoprefixer: ^10.4.21
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  vite: ^6.3.5
  vue: ^3.5.14
  zod: ^3.25.28
catalogs:
  react18:
    '@types/react': ^18.3.22
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1
  react19:
    '@types/react': ^19.1.5
    '@types/react-dom': ^19.1.5
    react: ^19.1.0
    react-dom: ^19.1.0
onlyBuiltDependencies:
  - sharp
