packages:
  - apps/*
  - packages/*
catalog:
  '@ark-ui/react': ^3.9.0
  '@ark-ui/vue': ^3.10.0
  '@types/react': ^18.3.4
  '@types/react-dom': ^18.3.0
  ai: ^3.3.20
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwind-merge: ^2.5.2
  tailwindcss: ^3.4.10
  tailwindcss-animate: ^1.0.7
  vite: ^5.4.2
  vue: ^3.4.38
  zod: ^3.23.8
