/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from "@tanstack/react-router"
import type {
  CreateServerFileRoute,
  ServerFileRoutesByPath,
} from "@tanstack/react-start/server"
import { createServerRootRoute } from "@tanstack/react-start/server"

import { Route as rootRouteImport } from "./app/__root"
import { Route as IndexRouteImport } from "./app/index"
import { Route as DocsSplatRouteImport } from "./app/docs/$"
import { ServerRoute as ApiSearchServerRouteImport } from "./app/api/search"

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchServerRoute = ApiSearchServerRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/docs/$": typeof DocsSplatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/docs/$": typeof DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/docs/$": typeof DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/docs/$"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/docs/$"
  id: "__root__" | "/" | "/docs/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSplatRoute: typeof DocsSplatRoute
}
export interface FileServerRoutesByFullPath {
  "/api/search": typeof ApiSearchServerRoute
}
export interface FileServerRoutesByTo {
  "/api/search": typeof ApiSearchServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  "/api/search": typeof ApiSearchServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: "/api/search"
  fileServerRoutesByTo: FileServerRoutesByTo
  to: "/api/search"
  id: "__root__" | "/api/search"
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSearchServerRoute: typeof ApiSearchServerRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/search": {
      id: "/api/search"
      path: ""
      fullPath: "/api/search"
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    "/docs/$": {
      id: "/docs/$"
      path: "/docs/$"
      fullPath: "/docs/$"
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    "/api/search": {
      id: "/api/search"
      path: "/api/search"
      fullPath: "/api/search"
      preLoaderRoute: typeof ApiSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    "/docs/$": {
      id: "/docs/$"
      path: "/docs/$"
      fullPath: "/docs/$"
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
  }
}

declare module "./app/index" {
  const createFileRoute: CreateFileRoute<
    "/",
    FileRoutesByPath["/"]["parentRoute"],
    FileRoutesByPath["/"]["id"],
    FileRoutesByPath["/"]["path"],
    FileRoutesByPath["/"]["fullPath"]
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath["/"]["parentRoute"],
    ServerFileRoutesByPath["/"]["id"],
    ServerFileRoutesByPath["/"]["path"],
    ServerFileRoutesByPath["/"]["fullPath"],
    unknown
  >
}
declare module "./app/api/search" {
  const createFileRoute: CreateFileRoute<
    "/api/search",
    FileRoutesByPath["/api/search"]["parentRoute"],
    FileRoutesByPath["/api/search"]["id"],
    FileRoutesByPath["/api/search"]["path"],
    FileRoutesByPath["/api/search"]["fullPath"]
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath["/api/search"]["parentRoute"],
    ServerFileRoutesByPath["/api/search"]["id"],
    ServerFileRoutesByPath["/api/search"]["path"],
    ServerFileRoutesByPath["/api/search"]["fullPath"],
    unknown
  >
}
declare module "./app/docs/$" {
  const createFileRoute: CreateFileRoute<
    "/docs/$",
    FileRoutesByPath["/docs/$"]["parentRoute"],
    FileRoutesByPath["/docs/$"]["id"],
    FileRoutesByPath["/docs/$"]["path"],
    FileRoutesByPath["/docs/$"]["fullPath"]
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath["/docs/$"]["parentRoute"],
    ServerFileRoutesByPath["/docs/$"]["id"],
    ServerFileRoutesByPath["/docs/$"]["path"],
    ServerFileRoutesByPath["/docs/$"]["fullPath"],
    unknown
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSearchServerRoute: ApiSearchServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
