name: Code check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable
        shell: bash

      - name: Setup Node & Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm dlx turbo test check:type
      - run: pnpm run lint