name: Code check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: biomejs/setup-biome@v2
        with:
          version: latest

      - run: biome ci --diagnostic-level=warn

  other:
    name: Test & TypeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable
        shell: bash

      - name: Setup Node & Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run test check:type --parallel