name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable
        shell: bash

      - name: Setup Node & Pnpm
        uses: actions/setup-node@v4
        with:
          node-version-file: ''
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --filter=shipbase-ui

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
